### ISSUE TITLE
Can git in RStudio work with GitHub Large File Storage

### ISSUE THREAD

**Issue by philipbaileynar** [namc-utah/namc-bug-db#177]
@courtwrightj01 is using the git client that plugs into R Studio (screenshots below). I think this is a great solution for NAMC analysts for working with git.

We are about to create a new repo to store the NAMC model R code (#176 ) and this repo has one extremely large file (1Gb). We would like to use GitHub's[ Large File Storage](https://git-lfs.github.com/) (LFS) for this purpose, but we are unsure if the R Studio git plugin can work with this feature. 

@David-Fowler can you please research if the R Studio git tool can be configured to work with GitHub's LFS please?

<img width="1487" alt="Screen Shot 2021-07-20 at 1 46 54 PM" src="https://user-images.githubusercontent.com/8645379/126529607-b2821d57-df81-40bc-b47b-467864f8ce2d.png">
<img width="1487" alt="Screen Shot 2021-07-20 at 1 46 32 PM" src="https://user-images.githubusercontent.com/8645379/126529623-28a64969-8c38-4c0d-a4e3-632c383bcf31.png">

FYI @MattReimer

**Comment by David-Fowler** [comment]
Agreed, that RStudio's built in git capabilities simplify the process of using github with R. Along the same lines I think it would be great to wrap up most of our code into official R packages (even if they are just github repo and not CRAN) thereby allowing simple package update routines to handle code distribution; leave things like the "glue" code / execution scripts that tie processes together in a separate repo. We can discuss this more later.

I do not believe R studio's git client works well with LFS at least 2 years ago it did not. The R community had made several alternative solutions at the time the most simple of which being an R package called piggyback. Piggyback handles large files by placing them on a Github repo as an asset and therefore is not handled by the git protocol at all. 2 simple R functions (pb_upload, pb_download) handle distribution of these asset files via the github API instead of git.

Another alternative is if we are going to use S3 buckets for other lab data (i.e. GIS files, etc.) should we not just place these large files there are well with link references in the repo back to their S3 address? The R code could technically use the S3 package to directly reference the files if desired.

**Comment by David-Fowler** [comment]
S3 storage is also ~5x less expensive than github LFS storage just to add another metric into our decision.

**Comment by David-Fowler** [comment]
Also, github does limit a repo size to 2GB so the method of using the piggyback R package only works if we are talking about less than 2GB of data per repo.

**Comment by philipbaileynar** [comment]
If the Rdata files are in an S3 bucket that is publicly readable, can R use them directly? Or will the user need to S3 sync the bucket down to their system first?

**Comment by David-Fowler** [comment]
The S3 package in R allows for direct access to files via R code. Numerous one liners exist to handle all reading / writing scenarios including copying the whole file into a temp file (or other file) on your system and using it from there. Or just streaming the file right into a local variable works as well.

I will add example code to an example repo demonstrating this.

**Comment by philipbaileynar** [comment]
The S3 package handles authentication?

**Comment by David-Fowler** [comment]
Yes. The S3 package can access storage that requires authentication. If we are moving ahead with amazon based accounts for the API my preference would be to use the same accounts to access the storage. I also believe the NAMCr package would be the best place to put NAMC based S3 support logic (essentially hiding the details of authentication in the NAMCr package, thereby reusing much of that code, and just present the necessary S3 functions to users as wrappers around the S3 package). This would allow:

- the storage backend to be changed at any point without having to change code potentially spread across all of our scripts
- keeps authentication and key handling in one place

Another option would be to split the NAMCr package up into 2 or more packages (api, authentication, storage etc) of which both storage and api packages require authentication as a dependency. Quick, easy to do, cleaner but could be done later.

**Comment by MattReimer** [comment]
We can either issue special IAM tokens for S3 access or tie the bucket credentials to the cognito accounts (something I haven't done but it seems pretty do-able)

https://docs.aws.amazon.com/IAM/latest/UserGuide/reference_policies_examples_s3_cognito-bucket.html

**Comment by David-Fowler** [comment]
If we go this route I would create 2 user roles for the bucket (one read-only and one read-write) then assign those roles to specific accounts on an as needed basis. Using roles for everything instead of using accounts directly is much easier to manage (especially as user pools grow and/or employee turnaround is high).

As for IAM tokens vs tying to access to cognito accounts: 

- I know IAM accounts and tokens work with the R S3 package (it requires an access key ID and an access key)
- I do not know if the keys provided via an oauth2 exchange via cognito would work even if the cognito account is tied to the bucket (this is a quick test which I can perform at any time).

**Comment by David-Fowler** [comment]
What would work is not using the oauth2 protocol, just using the cognito credentials directly (which could be stored/retrieved via R in the system password manager. This probably would be better than having to deal with / manage separate IAM tokens for bucket access (at least for normal day to day workflows).

Open to discussion.

**Comment by philipbaileynar** [comment]
Closing this issue. We put all rdata files in github except the big 1Gb one. We still need a strategy for handling this one file, but it felt silly to hold up progress on all the models for this one file. I put a readme.md in the repo where the big file should be.
