### ISSUE TITLE
SiteInfo SystemX Columns

### ISSUE THREAD

**Issue by philipbaileynar** [namc-utah/namc-bug-db#23]
There are three columns in `PilotDB.SiteInfo` with the name System1, System2 and System3. Can I confirm whether these tables are needed in the new database and if so if they can be moved to us lookup tables?

## System1

Existing Values:

| System1 |
| :--- |
| Lentic |
| NULL |
| Lotic |

New database table **ecosystems?**

## System2

| System2 |
| :--- |
| Reservoir |
| 37.2142 |
| Pond |
| Artificial |
| Spring \(flowing\) |
| NULL |
| 4 |
| Hanging garden |
| Lake |
| Seep |
| Stream |
| Lagoon |
| Marsh |
| Groundwater |
| Regulated River |
| Spring |
| Wetland |
| Spring \(static\) |

New database table: **unknown???**

## System3

| System3 |
| :--- |
| Salt marsh |
| Fresh playa |
| Pond |
| Limnocrene |
| Fresh marsh |
| NULL |
| Playa |
| Alcove pool |
| Fish pond |
| Rheocrene |
| Tinaja |
| Salt playa |
| Wet meadow |

New database table: **unknown???**

**Comment by philipbaileynar** [comment]
I am fine if `System2` becomes a lookup of the `PilotDB.TypeSystems` table. However, here are the current values of that table. Someone needs to specify which values from `PilotDB.System2` should get added to the lookup and also which ecosystem they belong to.

| SystemType | Ecosystem | Description | Visible |
| :--- | :--- | :--- | :--- |
| Lake | Lentic | NULL | true |
| Pond | Lentic | NULL | true |
| Regulated River | Lotic | NULL | true |
| Reservoir | Lentic | NULL | true |
| Spring \(flowing\) | Lotic | NULL | true |
| Spring \(static\) | Lentic | NULL | true |
| Stream | Lotic | NULL | true |
| Wetland | Lentic | NULL | true |

@courtwrightj01 you hinted that this information might not be needed in the new system. Please clarify.

**Comment by David-Fowler** [comment]
The TypeSystems and TypeEcosystems tables were created early on during the initial release of STREAM. At the time of creation NAMC had internal discussions and it was deemed that the only values of interest to us were those in these tables as they covered all the other types currently in the database.

 All data since STREAM was initially released has conformed to their values (they were foreign keys of siteinfo on the frontend database) and lookups to Sample Submission. What did not happen at the time was the complete cleanup of historical data. I would say we just need a map of the non-standard values that @philipbaileynar listed as being in System2 to the values in the TypeSystems table.
