### ISSUE TITLE
Samples and Projects

### ISSUE THREAD

**Issue by philipbaileynar** [namc-utah/namc-bug-db#24]
@David-Fowler had mentioned allowing samples to be related to multiple projects. While, most samples will only ever be related to a single project, this might provide flexibility going forward.

@courtwrightj01 and @Feldspar5 can you comment on whether you think this capability is necessary?

@David-Fowler can you please elaborate on some specific use cases of where allowing samples to be related to multiple projects might be valuable.

**Comment by courtwrightj01** [comment]
The only instances I can think of that this would be needed is for issues that are better solved by spatial queries of the data. I would say this is not necessary.

**Comment by David-Fowler** [comment]
While spatial queries should define the samples required for a given project I would argue the spatial boundary should be stored as a project field thereby allowing the project key relationships to handle the responsibility of gathering the relevant information when data is needed. One, this allows for a datetime of last project update (i.e. when samples are defined as part of a given project); two, project samples can be set to auto update at the end of every new box completion OR not update at all because of a static boolean flag being set at the project level (another field in the project table). 

Projects should be the storage point / origin of all spatial queries providing a central location to go to get whatever data is required (not having to store the spatial queries or boundaries separately somewhere else). Having the boundaries field in the projects table contain an array of spatial boundaries / points combined with one distinct update process / query (for determining new samples to assign to a project) will reduce physical computations (i.e. spatial queries are more computationally expensive than foreign key based joins) while also helping to organize referenced data.

As for multiple samples being assigned to a single project; by linking spatial queries to projects it is inherent in its definition especially as our data begins to be used for additional research. Projects can be the entry point for all data studies done internally, externally or graduate students; each new study gets a basic project definition containing at a minimum a name, contact point, and spatial points / boundaries of interest (again stored as a spatial array inside one spatial field).

Currently projects is a weak linkage of sample data that is not defined / updated well in existing processes. Linking it with the needed spatial capabilities should help solve both problems and helps solidify what a project actually is.

**Comment by philipbaileynar** [comment]
I really like @David-Fowler suggestion. It provides tons of flexibility without adding much complexity.

**Comment by philipbaileynar** [comment]
We are proceeding with the following:

* samples can be associated, none, one or multiple projects.
* for the first release, the samples associated with each project will be managed manually by NAMC. Lab staff will be able to add or remove samples from projects.

In subsequent releases we can consider dynamic projects that are defined by either a polygon or some kind of WHERE clause that constantly updates the samples associated with each project.
