### ISSUE TITLE
primary key on BugData

### ISSUE THREAD

**Issue by philipbaileynar** [namc-utah/namc-bug-db#31]
@David-Fowler I would like to revisit our plans for `sample.organisms`. Ihave issues with both the primary key and the notes (related to #29 ).

There are over 1m records in `PilotDB.BugData` and it's the area of the database that will grow fastest over time. My original design included an integer primary key on this table (to make the notes linkage more straightfoward), but now I'm thinking that a compound primary key would be more efficient:

```sample_id, taxonomy_id, life_stage_id, bug_size```

If we go this route then the `sample.organism_notes` table would need all these columns for each note. I don't like this bloat!

How would you feel if we pulled the notes into a JSON field in `sample.organisms`? If the notes will ever be used in a WHERE clause then we need to use JSONB. Views can be used to extract the note values into comma separated list etc.

Thoughts?

![schema](https://docs.google.com/drawings/d/e/2PACX-1vQJvDxsCu2AJN1T2NNF_kkBXPSUXzpc32gIcT5UE0-6Mmq_gH7CbjD64S1-DZ9ULJH8vIgJUxJ3vGnQ/pub?w=1839&h=1196)

**Comment by David-Fowler** [comment]
Hmmm.... that is pretty much how the latest version of data flowing through STREAM is outside of the keys actually being in place (it is treated like they are though). 

I have always been on the fence regarding switching to an integer primary key vs a compound key. I always disliked the compound key yet at the same time if the key was to be an integer a compound unique value constraint would have to be in place for the 4 fields anyway and they would still have to be used in insertion and  selection statements.

I kind of dislike the idea of placing these standardized notes into JSON especially if we are to house sub-counts along with each note. There have been a handful of projects over the years requiring filtering on these notes and given how the data is well known and organized JSON just seems unnecessary.

Do you dislike the idea of large integer primary keys or that the key is redundant because of the necessary 4 column unique constraint? While this will increase over time it is ~550k records per decade (if we go off the last decade). Metrics will actually outpace this table in the long run.

**Comment by philipbaileynar** [comment]
I am proceeding with the autogenerated primary key on `sample.organisms` with the lookup table for notes as preferred by @David-Fowler.
