### ISSUE TITLE
Is taxa with the same name possible?

### ISSUE THREAD

**Issue by philipbaileynar** [namc-utah/namc-bug-db#35]
Taxa code 19 "Oligochaeta" is at level SubClass. Its parent at the Class level appears to have the exact same name. Is this valid?

| Code | Kingdom | Phylum | Class | SubClass | ScientificName | TaxaLevel |
| :--- | :--- | :--- | :--- | :--- | :--- | :--- |
| 19 | Animalia | Annelida | Oligochaeta | Oligochaeta | Oligochaeta | SubClass |

```sql
SELECT Code, Kingdom, Phylum, Class, SubClass, ScientificName, TaxaLevel FROM Taxonomy where ScientificName = 'Oligochaeta'
```

**Comment by philipbaileynar** [comment]
Also, why is there no taxa for "Oligochaeta" at the Class level in the database?

**Comment by Feldspar5** [comment]
Both are invalid.  The class is now Clitellata.  Not certain how many sub-classes there are under that grouping though.  I just looked that up: there are three but we really do not ever use that level so not important.

Trip

**Comment by Feldspar5** [comment]
It might be because we use Clitellata and Oligochaeta is still there for historical reasons.  Or it might be that the team always IDs at finer resolution.


Trip

**Comment by David-Fowler** [comment]
I will jump in here with some history. ITIS has listings for Oligochaeta at both the Class and Subclass levels (both of which have become invalid over the years and both of which ITIS has designated Clitellata as the successor. NAMC had a mess of sub-trees under these names and our OTU specs were not consistent either (this was a source of OTU issues a few years back due to naming differences). When I renamed most of the trees to match ITIS (to fix the OTU issue at the time) I left some of this tree in place for original reference as Oligochaeta was and is still a source of scientific disagreement (even according to ITIS it is still unresolved). I did not want to loose the original reference in case internal lab discussions led to not following ITIS... but we needed a fix in the interim. Leaving this in place and overriding it in our roll up / tree walking / pivoted forms of the data allowed for this while awaiting lab decisions (@Feldspar5 this was all in those massive taxa difference speadsheets which were looked through a couple years ago).

All of the ID's done in the lab primarily used Oligochaeta at the subclass level (and we have numerous counts there). Where I wanted things to go, such that we follow ITIS on everything that we can, was to move these Oligochaeta counts offically to Clitellata (which I believe is the case in the pivoted tables). One things which I think now would be beneficial for rare cases of disagreement like this is to add another column to the pivoted table referring to the taxa synonym (from the synonym table) used during (ID, import etc.). This way when trees / names change we always have reference to the original allowing us to change our minds at some future point.

**Comment by Feldspar5** [comment]
Gordian knot time, I think.

NAMC does not care about a subclass in the class Clitellata/Oligochaeta.  All sub-class IDs in out database under that taxon are likely errors and should be kept at class.  By all means, follow your plan for the pivot-synonym-Oligo-Clitellata crossover, but forget the sub-class.  There is nothing relevant to analysis or modeling at that taxonomic level and never will be.

Trip

**Comment by philipbaileynar** [comment]
Closing this outdated issue. Other tickets are dealing with taxonomic hierarchy, notablly #131
