### ISSUE TITLE
BugOMatter contains missing sample

### ISSUE THREAD

**Issue by philipbaileynar** [namc-utah/namc-bug-db#38]
`PilotDB.BugOMatter` contains sample ID 16988 that does not exist in `PilotDB.BugSample`.

Does anyone know why? Or how I should handle this.

For now, I am going to omit this BugOMatter record from the new system until someone tells me where I can find this sample!

```sql
SELECT B.*, BS.SampleID
FROM BugOMatter B
         LEFT JOIN BugSample BS on B.SampleID = BS.SampleID
WHERE BS.SampleID IS NULL;
```

**Comment by David-Fowler** [comment]
If samples like this present themselves in the "other sample type" tables it is due to a sample / box deletion which missed these accessory tables. It was rare but I have tracked a few in the database. They are orphan and never would get picked up in a query but are garbage data and should be deleted.

**Comment by philipbaileynar** [comment]
@David-Fowler just confirming that this cropped up in BugData too.

Total records in bug data is 2,014,009 but those with sample IDs that occur in BugSample is 2,013,997. I will proceed by omitting those records in BugData that have sample IDs that are not in BugSample.

**Comment by David-Fowler** [comment]
Yes. That is the same issue (improper deletes) and those bugdata records should be deleted as well.

**Comment by Feldspar5** [comment]
correct
