### ISSUE TITLE
To underscore or not to underscore?

### ISSUE THREAD

**Issue by philipbaileynar** [namc-utah/namc-bug-db#47]
OK, this train is leaving the station. We need to decide on our naming convention for database tables and columns. The old SQLServer database used [PascalCase](https://en.wikipedia.org/wiki/Camel_case). The Postgres standard that I have adopted in the [new schema](https://github.com/namc-utah/namc-bug-db/blob/master/docker/postgres/initdb/01_SCHEMA.sql) thus far is [snake case](https://en.wikipedia.org/wiki/Snake_case). Here's just one example for drift data:

```sql
CREATE TABLE sample.drift (
    sample_id           INT NOT NULL PRIMARY KEY,
    net_area            FLOAT,
    net_duration        FLOAT,
    stream_depth        FLOAT,
    net_depth           FLOAT,
    net_velo            FLOAT,
    notes               TEXT,
    updated_date        TIMESTAMPTZ NOT NULL DEFAULT now(),
);
```

I truly don't mind which we use. But we need to decide now, before we write 100,000 lines of code that refer to the database object names. Here the pros and cons that I see:

## Reasons to use Pascal Case

* Familiar to NAMC staff (cannot overstate how valuable this is)
* Less verbose (those underscores add up)

## Reasons to use Snake Case

* Postgres standard
* Somewhat counterintuitively, switching conventions will ensure any code that has not been tested against the new system will intentionally break and force a review.

## Technical Reasons why this doesn't matter

* SQL is non-case sensitive, so underscores aside, internally Postgres converts all names to lower case.
* Different elements of the system will use different technologies and will implement their own standards. The API will probably use Pascal case while the user interface will adopt JavaScripts lower camel case. R [doesn't have an official standard](https://en.wikipedia.org/wiki/Naming_convention_(programming)#R).

Everyone please weigh in... This is your database and I want you to be excited about using it. My sense is that snake case is going to annoy NAMC staff.

**Comment by courtwrightj01** [comment]
My vote would be Pascal case but if others have strong preferences I could go either way

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by Feldspar5** [comment]
I support Pascal.

**Comment by philipbaileynar** [comment]
Good news... bad news...

I have experimented with Pascal case and I don't think it's going to be practical. Postgres forces lower case names and then when you attempt to retrieve data you end up with all lower case:

<img width="358" alt="Screen Shot 2021-01-06 at 2 35 22 PM" src="https://user-images.githubusercontent.com/8645379/103831460-fab8cf00-5030-11eb-9639-252ee4dae6ce.png">

I find this illegible and a deal breaker. The screenshot is from Python, but the same will be true for all tools through which you programmatically interact with the database. SQL is case insensitive, so queries will work! but it is just too hard to work with the column names all converted to lower case.

The good news is that we are wrapping the database in two layers of technology. The database will be behind an API and NAMC staff will access it via an R package. Both the API and the R package can use Pascal case (if we want). But for now, the database will remain in camel case.

Happy to discuss if you have questions.

**Comment by Feldspar5** [comment]
But what a great password generator…

**Comment by David-Fowler** [comment]
I neglected to comment on this to begin with mostly as I knew at the time I was going to be the odd one out. My preference for databases has always been snake_case specifically because most databases are case insensitive and therefore most tools you plug into them will never spit out pascal or camel case fields (including things like in management studio where you "Select All" on a table and the sql coming out is always all CAPS). 

By using snake case you can ensure readability no matter what tool you connect to the DB. And by choosing the databases internal case (caps or lower) you can also ensure the tools provide the original case as well.

Honestly, this is one of those topics that some groups could fight about all day and not reach a result and all the points @philipbaileynar  originally brought up are all valid especially familiarity. That said we are changing enough fields and tables as well as there names that I would say now is the time to adopt consistency and worry less about how we had things historically. Verbiage, plural vs singular and prefix/suffix designations are the primary naming convention topics that need to be consistent. 

As @philipbaileynar  mentioned the API can be the same or different to the DB. With regard to direct sql queries I feel with the right editor and tab completion enabled the extra characters in snake_case can be neglected as they don't need to be physically typed out... but again everyone has a different preference when it comes to usability.

**Comment by courtwrightj01** [comment]
Ok, given all that snake case is fine with me!

**Comment by Feldspar5** [comment]
I can support snake casing.  Seems more productive than spending time debating relative merits of the options.

**Comment by philipbaileynar** [comment]
Remember... depending on where we go... you may never know that the database uses snake case. If your sole interaction with the database is through a rich R package that provides all the data that you need you may never need to write SQL commands in SQL Server Management Studio again! This R package can use Pascal case.

**Comment by David-Fowler** [comment]
Exactly. I second @philipbaileynar and really, really want us to move away from independent sql queries and to only work through the API. I really think it is possible and that we can benefit a lot from it.
