### ISSUE TITLE
Dates and timestamps in the API

### ISSUE THREAD

**Issue by philipbaileynar** [namc-utah/namc-bug-db#67]
@MattReimer what format should I return dates and timestamps in the API? Currently I'm just dumping them all as strings... 

Data use cases:

1. Samples are collected on dates. There are a few legacy samples that have times stored in a separate column, but for the most part sample dates are stored in a PostGres date column.
2. Most database tables have `date_created` and `date_updated` columns that are stored as Postgres TimeStamps.

End Use cases:

1. Obviously the UI can handle TimeStamps and do the right thing with them.
2. How should the time-stamps be delivered to R? Does R have good timestamp handling or should we pre-convert to string (ISO or otherwise) for the R API endpoints?

FYI @David-Fowler

**Comment by David-Fowler** [comment]
I would stick to returning the standard ISO 8601 which in basic form looks like: yyyy-mm-dd hh:mm:ss.ms+-TZ. I believe this is the standard output anyway so no conversion should be necessary.

Whether the data has timezone or not attached will depend on the field (i.e. date_created / updated might have it while the sample dates may or may not). If we have timezone data I would attached it.

That ISO standard we already use for everything. While R can handle any format date/time data (and I could even hijack that in the R API to convert on the fly before passing it to the user) sticking to what we have already is probably easiest. 

Also, a slight variation of that ISO standard sometimes represents the timezone in string format (i.e. PST, MST etc). If that is easier it will work as well.

**Comment by MattReimer** [comment]
Yeah. This sounds good. When I start from scratch I like to use standard linux ms timestamps for everything in the DB and then convert it as it's displayed. This is a little messier since we're dealing with incoming data. 

JS and GraphQL don't care what you use. just:

1. Be as consistent as you can. Treat dates the same everywhere or things get messy fast, especially going from UI to DB and back again. We should make sure that all our scripts handle dates correctly too. Whatever that means.
3. Do the extra work to sort out the timezone business. We've got to have bulletproof methods for determining if the date we're looking at has a timezone attached and when it doesn't. 

Dates are the hardest easy-looking problem in computer science. It always seems easy. It always has gotchas.
