### ISSUE TITLE
BugData Uniqueness

### ISSUE THREAD

**Issue by philipbaileynar** [namc-utah/namc-bug-db#72]
We are proposing a unique key on the table `sample.organisms` that replaces `PilotDB.BugData` across the following columns:

* SampleID
* TaxonomyID
* LifeStageID
* BugSize

The are 13,135 combinations of these keys that have more than one record associated with them. Here are the top ten worst offending combinations:

| SampleID | Code | LifeStage | BugSize | RecordCount |
| :--- | :--- | :--- | :--- | :--- |
| 156037 | 184 | L | NULL | 9 |
| 152857 | 121 | L | NULL | 8 |
| 152858 | 484 | L | NULL | 8 |
| 152858 | 250 | L | NULL | 8 |
| 152857 | 135 | L | NULL | 8 |
| 169494 | 184 | L | NULL | 7 |
| 152858 | 58 | A | NULL | 7 |
| 152857 | 262 | L | NULL | 7 |
| 152858 | 647 | A | NULL | 7 |
| 152857 | 1076 | A | NULL | 7 |

```sql
SELECT TOP 10 SampleID, Code, LifeStage, BugSize, Count(*) RecordCount FROM BugData GROUP BY SampleID, Code, LifeStage, BugSize HAVING Count(*) > 1 ORDER BY RecordCount DESC;
```

And here are all 9 records for the worst offending combination:

| SampleID | Code | RowIndex | LifeStage | BugSize | SplitCount | BigRareCount | Notes | Valid |
| :--- | :--- | :--- | :--- | :--- | :--- | :--- | :--- | :--- |
| 156037 | 184 | 2 | L | NULL | 7 | 0 | NULL | NULL |
| 156037 | 184 | 3 | L | NULL | 7 | 0 | NULL | NULL |
| 156037 | 184 | 4 | L | NULL | 7 | 0 | NULL | NULL |
| 156037 | 184 | 5 | L | NULL | 7 | 0 | NULL | NULL |
| 156037 | 184 | 6 | L | NULL | 7 | 0 | NULL | NULL |
| 156037 | 184 | 7 | L | NULL | 7 | 0 | NULL | NULL |
| 156037 | 184 | 8 | L | NULL | 7 | 0 | NULL | NULL |
| 156037 | 184 | 9 | L | NULL | 7 | 0 | NULL | NULL |
| 156037 | 184 | 10 | L | NULL | 7 | 0 | NULL | NULL |

```sql
SELECT * FROM BugData WHERE SampleID = 156037 AND Code = 184 AND LifeStage = 'L' AND BugSize IS NULL
```

# Options

1. Drop the unique index that we propose
2. Combine the duplicate records some how.
3. Discard some or all of the records.

**Comment by David-Fowler** [comment]
All the records need to be summed together for a given unique combination. Prior to 2010 and a few cases after added additional records when new additions were found instead of doing the math and combining them I to one record. All current metric / calculations involving bugdata first sum across the unique indexes to get single records before proceeding.

Both split count and bigrare fields need to be summed into single records.

**Comment by philipbaileynar** [comment]
@David-Fowler presumably there is some kind of lab workflow that produces these duplicates. Going forward, do you envision that new user interface incrementing the existing counts rather than inserting duplicates?

**Comment by David-Fowler** [comment]
The lab workflow that produced these duplicates is ancient. The current STREAM UI does the proper math when necessary (though in normal workflows via the UI it is not even necessary as the taxonomists are editing them directly).

Prior to STREAM entry was done manually by hand from paper sheet to database table. The transcriber literally took each hand written paper entry and added it to the DB table. Many times the taxonomist would replicate entries when they found additional taxa of the same uniqueness (instead of going back up their sheet and modifying previous entries). Hence... replicates in the DB.

**Comment by philipbaileynar** [comment]
This worked like a charm. organisms are going into the new database now that the uniqueness is resolved.
