### ISSUE TITLE
Reference table design

### ISSUE THREAD

**Issue by philipbaileynar** [namc-utah/namc-bug-db#86]
@David-Fowler finally putting references into the database so we can generate the reports (see screenshot below).

I could go simple like the design below... or break out the references into more fields to provide granularity similar to bibliographic tools (authors, year, title, publication).

I would like to keep it simple for now. Are you OK with that or do you see any immediate needs to manipulate the separate parts of a reference?

```sql
CREATE TABLE taxa.references
(
    reference_id SMALLINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    citation     TEXT        NOT NULL,
    url          TEXT,
    created_date TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_date TIMESTAMPTZ NOT NULL DEFAULT now()
);
```

<img width="1019" alt="Screen Shot 2021-03-05 at 2 17 50 PM" src="https://user-images.githubusercontent.com/8645379/110180026-eccbc400-7dbd-11eb-8e77-081e63431a5a.png">

**Comment by David-Fowler** [comment]
I think we can make that work. My only concern is the code that pulls new taxa /resources into the db may need to clean, standardize and format the references before passing them back up the API as the references themselves come from various sources each with potential differences. To match like for like so we are not replicating entries the citation format needs to be perfectly in sync otherwise matches won't be found.

**Comment by philipbaileynar** [comment]
What about splitting out:

* authors
* year
* title
* publication
* url

I don't want to go crazy and write an entire bibliographic system!

**Comment by David-Fowler** [comment]
I agree with not wanting to get too carried away. I think splitting out those 5 should work. Most of the time Title and Year would provide a good match and the extras are enough to satisfy all reference criteria. Let's try it.
